//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspectPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commission()
        {
            this.Inspection = new HashSet<Inspection>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public int EmployeeId { get; set; }
        public System.Guid EmployeeGuid { get; set; }
        public int CustomerId { get; set; }
        public System.Guid CustomerGuid { get; set; }
        public int LocationId { get; set; }
        public Nullable<System.Guid> LocationGuid { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspection { get; set; }
    }
}
