//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.QuestionItem = new HashSet<QuestionItem>();
        }
    
        public int Id { get; set; }
        public int Version { get; set; }
        public System.Guid Guid { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int QuestionTypeId { get; set; }
        public System.Guid QuestionTypeGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionItem> QuestionItem { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
